import { Order } from '../models/order.model';

export const MOCK_ORDERS: Order[] = [
  { id: 'ORD-1001', customerName: 'TechVision Inc.',    customerEmail: 'orders@techvision.com',   items: [{ productName: 'Server Rack 42U', qty: 2, unitPrice: 1200 }, { productName: 'UPS 3000VA', qty: 2, unitPrice: 450 }],                      total: 3300,  status: 'delivered',  region: 'North America', createdAt: '2024-04-01', updatedAt: '2024-04-05' },
  { id: 'ORD-1002', customerName: 'Global Logistics',   customerEmail: 'proc@globallog.com',     items: [{ productName: 'Barcode Scanner', qty: 10, unitPrice: 89 }],                                                                            total: 890,   status: 'shipped',    region: 'Europe',        createdAt: '2024-04-03', updatedAt: '2024-04-10' },
  { id: 'ORD-1003', customerName: 'HealthPlus Corp.',   customerEmail: 'supply@healthplus.com',  items: [{ productName: 'Network Switch 24P', qty: 5, unitPrice: 320 }, { productName: 'Cat6 Cable 100m', qty: 20, unitPrice: 35 }],             total: 2300,  status: 'processing', region: 'Asia Pacific',  createdAt: '2024-04-05', updatedAt: '2024-04-12' },
  { id: 'ORD-1004', customerName: 'RetailWorld',        customerEmail: 'buyers@retailworld.com', items: [{ productName: 'POS Terminal', qty: 8, unitPrice: 650 }],                                                                              total: 5200,  status: 'pending',    region: 'North America', createdAt: '2024-04-08', updatedAt: '2024-04-08' },
  { id: 'ORD-1005', customerName: 'EduSmart Solutions', customerEmail: 'admin@edusmart.com',     items: [{ productName: 'Laptop 15"', qty: 25, unitPrice: 780 }, { productName: 'Wireless Mouse', qty: 25, unitPrice: 22 }],                    total: 20050, status: 'delivered',  region: 'Europe',        createdAt: '2024-04-02', updatedAt: '2024-04-09' },
  { id: 'ORD-1006', customerName: 'FinServ Group',      customerEmail: 'ops@finserv.com',        items: [{ productName: 'Firewall Appliance', qty: 3, unitPrice: 2100 }],                                                                      total: 6300,  status: 'shipped',    region: 'North America', createdAt: '2024-04-06', updatedAt: '2024-04-13' },
  { id: 'ORD-1007', customerName: 'ManufactureX',       customerEmail: 'supply@mfgx.com',        items: [{ productName: 'Industrial Tablet', qty: 12, unitPrice: 430 }, { productName: 'Rugged Case', qty: 12, unitPrice: 55 }],               total: 5820,  status: 'cancelled',  region: 'Asia Pacific',  createdAt: '2024-04-04', updatedAt: '2024-04-07' },
  { id: 'ORD-1008', customerName: 'CloudNine Ltd.',     customerEmail: 'it@cloudnine.io',        items: [{ productName: 'Storage NAS 24TB', qty: 4, unitPrice: 1850 }],                                                                       total: 7400,  status: 'processing', region: 'Europe',        createdAt: '2024-04-09', updatedAt: '2024-04-14' },
  { id: 'ORD-1009', customerName: 'SmartCity Gov.',     customerEmail: 'ict@smartcity.gov',      items: [{ productName: 'IP Camera 4K', qty: 30, unitPrice: 210 }, { productName: 'NVR 32-Channel', qty: 3, unitPrice: 900 }],                 total: 9000,  status: 'pending',    region: 'Middle East',   createdAt: '2024-04-10', updatedAt: '2024-04-10' },
  { id: 'ORD-1010', customerName: 'Apex Retail',        customerEmail: 'order@apexretail.com',   items: [{ productName: 'Receipt Printer', qty: 15, unitPrice: 185 }],                                                                        total: 2775,  status: 'delivered',  region: 'Africa',        createdAt: '2024-04-01', updatedAt: '2024-04-06' },
  { id: 'ORD-1011', customerName: 'BioLab Research',   customerEmail: 'equip@biolab.org',       items: [{ productName: 'Workstation Pro', qty: 6, unitPrice: 2200 }],                                                                         total: 13200, status: 'shipped',    region: 'Europe',        createdAt: '2024-04-07', updatedAt: '2024-04-15' },
  { id: 'ORD-1012', customerName: 'SkyBridge Telecom', customerEmail: 'procurement@skybt.com',  items: [{ productName: 'Fiber Media Converter', qty: 50, unitPrice: 65 }, { productName: 'SFP Module', qty: 50, unitPrice: 45 }],             total: 5500,  status: 'processing', region: 'Asia Pacific',  createdAt: '2024-04-11', updatedAt: '2024-04-16' },
  { id: 'ORD-1013', customerName: 'AquaFarm Co.',       customerEmail: 'ops@aquafarm.com',       items: [{ productName: 'Environmental Sensor', qty: 20, unitPrice: 130 }],                                                                   total: 2600,  status: 'pending',    region: 'Asia Pacific',  createdAt: '2024-04-12', updatedAt: '2024-04-12' },
  { id: 'ORD-1014', customerName: 'MedTech Supplies',  customerEmail: 'buy@medtech.com',        items: [{ productName: 'Medical Tablet 10"', qty: 18, unitPrice: 560 }],                                                                     total: 10080, status: 'delivered',  region: 'North America', createdAt: '2024-04-02', updatedAt: '2024-04-08' },
  { id: 'ORD-1015', customerName: 'Urban Builds',       customerEmail: 'site@urbanbuilds.com',   items: [{ productName: 'Smart Thermostat', qty: 40, unitPrice: 95 }, { productName: 'Smart Lock', qty: 40, unitPrice: 120 }],               total: 8600,  status: 'shipped',    region: 'Europe',        createdAt: '2024-04-08', updatedAt: '2024-04-16' },
  { id: 'ORD-1016', customerName: 'Nexus Ventures',     customerEmail: 'admin@nexusv.com',       items: [{ productName: 'LED Display 55"', qty: 5, unitPrice: 980 }],                                                                         total: 4900,  status: 'cancelled',  region: 'North America', createdAt: '2024-04-05', updatedAt: '2024-04-09' },
  { id: 'ORD-1017', customerName: 'Harbor Freight',     customerEmail: 'mgr@harborfreight.com',  items: [{ productName: 'Inventory Scanner', qty: 22, unitPrice: 145 }],                                                                      total: 3190,  status: 'processing', region: 'North America', createdAt: '2024-04-13', updatedAt: '2024-04-17' },
  { id: 'ORD-1018', customerName: 'SolarTech Africa',   customerEmail: 'supply@solartech.co',   items: [{ productName: 'IoT Gateway', qty: 8, unitPrice: 310 }, { productName: 'Solar Controller', qty: 8, unitPrice: 190 }],               total: 4000,  status: 'pending',    region: 'Africa',        createdAt: '2024-04-14', updatedAt: '2024-04-14' },
  { id: 'ORD-1019', customerName: 'PharmaNet',          customerEmail: 'it@pharmanet.com',       items: [{ productName: 'Thin Client', qty: 30, unitPrice: 280 }],                                                                            total: 8400,  status: 'delivered',  region: 'Europe',        createdAt: '2024-04-03', updatedAt: '2024-04-10' },
  { id: 'ORD-1020', customerName: 'AutoDrive Systems',  customerEmail: 'parts@autodrive.com',    items: [{ productName: 'Industrial PC', qty: 10, unitPrice: 750 }, { productName: 'HMI Panel 7"', qty: 10, unitPrice: 320 }],               total: 10700, status: 'shipped',    region: 'Asia Pacific',  createdAt: '2024-04-10', updatedAt: '2024-04-18' },
];
